<div class="container">
	<div class="col-md-10">
	
	<div class="row row-offcanvas row-offcanvas-right">
		<h1 class="featurette-heading">Crença</h1>
		<hr class="featurette-divider">
		<center><p align="justify"><b>I – AUTORIDADE</b></p><center>
		<p align="justify"><em>1. Cristo como o Senhor</em></p>
		<p align="justify">A fonte suprema da autoridade cristã é o Senhor Jesus Cristo. Sua soberania emana da eterna divindade e poder – Como o unigênito filho de Deus Supremo – de Sua redenção vicária e ressurreição vitoriosa. Sua autoridade é a expressão de amor justo, sabedoria infinita e santidade divina, e se aplica à totalidade da vida. Dela procede a integridade do propósito cristão, o poder da dedicação cristã, a motivação de lealdade cristã. Ela exige a obediência aos mandamentos de Cristo, dedicação ao Seu serviço, fidelidade ao Seu reino e a máxima devoção à Sua Pessoa, como o Senhor vivo.</p>
		<p align="justify">A suprema fonte de autoridade é o Senhor Jesus Cristo, e toda a esfera da vida esta sujeita a Sua soberania.</p><br/>
		<p align="justify"><em>2. As Escrituras</em></p>
		<p align="justify">A Bíblia fala com autoridade porque é a palavra de Deus. É a suprema regra de fé e prática porque é testemunha fidedigna e inspirada dos atos maravilhosos de Deus através da revelação de Si mesmo e da redenção, sendo tudo patenteado na vida, nos ensinamentos e na obra Salvadora de Jesus Cristo. As Escrituras revelam a mente de Cristo e ensinam o significado de seu domínio. Na sua singular e una revelação da vontade divina para humanidade, a Bíblia é a autoridade final que atrai as pessoas a Cristo e as guia em todas as questões de fé cristã e dever moral. O indivíduo tem que aceitar a responsabilidade de estudar a Bíblia, com a mente aberta e com atitude reverente, procurando o significado de sua mensagem através de pesquisa e oração, orientando a vida debaixo de sua disciplina e instrução.</p>
		<p align="justify">A Bíblia como revelação inspirada da vontade divina, cumprida e completada na vida e nos ensinamentos de Jesus Cristo, é a nossa regra autorizada de fé e prática.</p><br/>
		<p align="justify"><em>3. O Espírito Santo</em></p>
		<p align="justify">O Espírito Santo é a presença ativa de Deus no mundo e, particularmente, na experiência humana. É Deus revelando Sua pessoa e vontade ao homem. O Espírito, portanto é a voz da autoridade divina. É o Espírito de Cristo, e Sua autoridade é a vontade de Cristo. Visto que as Escrituras são o produto de homens que, inspirados pelo Espírito, falaram por Deus, a verdade da Bíblia expressa a vontade do Espírito, compreendida pela iluminação do Mesmo. Ele convence os homens do pecado, da justiça e do juízo, tornando, assim, efetiva a salvação individual, através da obra salvadora de Cristo. Ele habita no coração do crente, como advogado perante Deus e intérprete para o homem. Ele atrai o fiel para a fé e a obediência e, assim, produz na sua vida os frutos da santidade e do amor.</p>
		<p align="justify">Espírito procura alcançar vontade e propósito divinos entre os homens. Ele dá aos cristãos poder e autoridade para o trabalho do reino e santifica e preserva os redimidos, para o louvo de Cristo; exige uma submissão livre e dinâmica à autoridade de Cristo, e uma obediência criativa e fiel à palavra de Deus.</p>
		<p align="justify">O Espírito Santo é o próprio Deus revelando Sua pessoa e vontade aos homens. Ele, portanto interpreta e confirma a voz da autoridade divina.</p><br/>
		<center><p align="justify"><b>II – O INDIVÍDUO</b></p><center>
		<p align="justify"><em>1. Seu Valor</em></p>
		<p align="justify">A Bíblia revela que cada ser humano é criado à imagem de Deus; é único, precioso e insubstituível. Criado ser racional, cada pessoa é moralmente responsável perante Deus e o próximo. O homem como indivíduo é distinto de todas as outras pessoas. Como pessoa, ele é unido aos outros no fluxo da vida, pois ninguém vive nem morre por si mesmo.</p>
		<p align="justify">A Bíblia revela que Cristo morreu por todos os homens. O fato de ser o homem criado à imagem de Deus e de Cristo morrer para salvá-lo é a fonte da dignidade e do valor humano. Ele tem direito, outorgado por Deus, de ser reconhecido e aceito como indivíduo sem distinção de raça, cor, credo ou cultura; de ser parte digna de respeitada da comunidade; de ter a plena oportunidade de alcançar o seu potencial.</p>
		<p align="justify">Cada indivíduo foi criado à imagem de Deus e, portanto, merece respeito e consideração como uma pessoa de valor e dignidade infinita.</p><br/>
		<p align="justify"><em>2. Sua Competência</em></p>
		<p align="justify">O indivíduo, porque criado à imagem de Deus, torna-se responsável por suas decisões morais e religiosas. Ele é competente, sob a orientação do Espiríto Santo, para formular a própria resposta à chamada divina ao evangelho de Cristo, para a comunhão com Deus, para crescer na graça e conhecimento de nosso Senhor. Estreitamente ligada a essa competencia está a responsabilidade de procurar a verdade e, encontrado-a, agir conforme essa descoberta e de partilhar a verdade com outros. Embora não se admita coação no terreno religioso, o cristão não tem a liberdade de ser neutro em questões ee conciência e convicção.</p>
		<p align="justify">Cada pessoa é competente e responsável perante Deus, nas próprias decisões e questões morais e religiosas.</p><br/>
		<p align="justify"><em>3. Sua Liberdade</em></p>
		<p align="justify">Os batistas consideram como inalienável a liberdade de consciência, a plena liberdade de religião de todas as pessoas. O homem é livre para aceitar ou rejeitar a religião; escolher ou mudar sua crença; propagar e ensinar a verdade como a entenda, sempre respeitando direitos e convicções alheios; cultuar a Deus tanto a sós quanto publicamente; convidar outras pessoas a participarem nos cultos e outra atividades de sua religião; possuir propriedade e quaisquer outros bens necessários à propagação de sua fé. Tal liberdade não é privilégio para ser concedido, rejeitado ou meramente tolerado – nem pelo Estado, nem por qualquer outro grupo religioso – é um direito outorgado por Deus.</p>
		<p align="justify">Cada pessoa é livre perante Deus em todas as questões de consciência e tem o direito de abraçar ou rejeitar a religião, bem como de testemunhar sua fé religiosa, respeitando os direitos dos outros.</p><br/>
		<center><p align="justify"><b>III – A VIDA CRISTÃ</b></p></center>
		<p align="justify"><em>1. A Salvação pela Graça</em></p>
		<p align="justify">A graça é a provisão misericordiosa de Deus para a condição do homem perdido. O homem no seu estado natural é egoísta e orgulhoso; ele está na escravidão de satanás e espiritualmente morto em transgressões e pecados. Devido à sua natureza pecaminosa, o homem não pode salvar-se a si mesmo. Mas Deus tem uma atitude benevolente em relação a todos, a pesar da corrupção moral e da rebelião. A salvação não é o resultado dos méritos humanos, antes emana de propósito e iniciativa divinos. Não vem através de mediação sacramental, nem de treinamento moral, mas como resultado da misercórdia e poder divinos. A salvação do pecado é a dádiva de Deus através de Jesus Cristo, condicionada, apenas, pelo arrependimento em relação da Deus, pela fé em Jesus Cristo, e pela entrega incondicional a Ele como Senhor.</p>
		<p align="justify">A Salvação, que vem através da graça, pela fé, coloca o individuo em união vital e transformadora com Cristo, e se caracteriza por uma vida de santidade e boas obras. A mesma graça, por meio da qual a pessoa alcança a salvação, dá certeza e a segurança do perdão contínuo de Deus e de Seu auxilio na vida cristã.</p>
		<p align="justify">A salvação é dádiva de Deus através de Jesus Cristo, condicionada, apenas, pela fé em cristo e rendição à Soberania Divina.</p><br/>
		<p align="justify"><em>2. As Exigências do Discipulado</em></p>
		<p align="justify">O aprendizado cristão inicia-se com a entrega a Cristo, como Senhor. Desenvolve-se à proporção que a pessoa tem comunhão com Cristo e obedece aos Seus mandamentos. O discípulo aprende a verdade em Cristo, somente por obedecê-la. Essa obediência exige a entrega das ambições e dos propósitos pessoais e a obediência à vontade do Pai. A obediência levou Cristo à cruz e exige de cada discípulo que se tome a própria cruz e siga a Cristo.</p>
		<p align="justify">O levar a cruz, ou negar-se a si mesmo, expressa-se de muitas maneiras na vida do discípulo. Este procurará, primeiro, o reino de Deus. Sua lealdade suprema será a Cristo. Ele será fiel em cumpri o mandamento cristão. Sua vida pessoal manifestará autodisciplina, pureza, integridade e amor cristão em todas as relações que tem com os outros. O discipulado é completo.</p><br/>
		<p align="justify"><em>3. O Sacerdócio do Crente</em></p>
		<p align="justify">Cada homem pode ir diretamente a Deus em busca de perdão, através do arrependimento e da fé. Ele não necessita para isso de nenhum outro indivíduo, nem mesmo de igreja. Há um só mediador entre Deus e os homens, Jesus. Depois de tornar-se crente a pessoa tem acesso direto a Deus, através de Cristo. Ela entra no sacerdócio real que lhe outorga o privilegio de servir a humanidade em nome de Cristo. Deverá partilhar com os homens a fé que acalenta e servi-los em nome e no espírito de Cristo. O Sacerdócio do crente, portanto, significa que todos os cristãos são iguais perante Deus e na fraternidade da igreja local.</p>
		<p align="justify">Cada cristão, tendo acesso direto a Deus através de Cristo, é seu próprio sacerdote e tem a obrigação de servir de sacerdote de Cristo em benefício de outras pessoas.</p><br/>
		<p align="justify"><em>4. O Cristão e Seu Lar</em></p>
		<p align="justify">O lar foi constituído por Deus como unidade básica da sociedade. A formação de lares verdadeiramente cristãos deve merecer o interesse particular de todos. Devem ser constituídos da união de dois seres cristãos, dotados de maturidade emocional, espiritual e física e unidos por um amor profundo e puro. O casal deve partilhar ideais e ambições semelhantes e ser dedicado à criação dos filhos na instrução e disciplina divinas. Isso exige o estudo regular da Bíblia e a prática do culto doméstico. Nesses lares o espírito de Cristo está presente em todas as relações da família.</p>
		<p align="justify">As igrejas tem a obrigação de preparar jovens para o casamento, treinar e auxiliar os pais nas suas responsabilidades, orientar pais e filhos na provações e crises da vida, assistir àqueles que sofrem em lares desajustados, e ajudar os enlutado e encanecidos a encontrarem sempre um significado na vida.</p>
		<p align="justify">O lar é básico, no propósito de Deus para o bem estar da humanidade, e o desenvolvimento da família deve ser de supremo interesse para todos os cristãos.</p><br/>
	</div>
	</div>
	
	<div class="col-md-2">
		<div class="list-group"><center>
			<a href="<?= site; ?>/sobre/historia" class="list-group-item">Nossa história</a>
			<a href="<?= site; ?>/sobre/visao" class="list-group-item">Visão e missão</a>
			<a href="<?= site; ?>/sobre/crenca" class="list-group-item">Crença</a>
			<a href="<?= site; ?>/sobre/propositos" class="list-group-item">Propósitos</a>
			<a href="<?= site; ?>/sobre/instituicao" class="list-group-item">Estatuto e Instituição</a>
			<a href="<?= site; ?>/sobre/ministerios" class="list-group-item">Ministérios</a>
		</center></div>
	</div>
</div>